#!/bin/bash
set -eo pipefail

repo=${1%:*}
tag=${1#*:}
cmd="$2"
folder="$HOME/.docker-internals"
path="$folder/$repo/$tag"
script_path=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
init=false

function help(){
    echo "Usage: $(basename $0) <repo>/<image>:<tag> <command>"
    exit 0
}
[[ $1 =~ ^[a-z_-]+/[a-z_-]+:[a-z_-]+$ ]] || help

[ -n "$cmd" ] || help

if [ ! -d "$path" ];then
    eval "$script_path/download-image $repo:$tag"
    init=true    
fi

if [ "$init" = true ];then
    echo "nameserver 8.8.8.8" > $path/etc/resolv.conf

    sudo chroot "$path" mknod /dev/null c 1 3
    sudo chroot "$path" mknod /dev/zero c 1 5
    sudo chroot "$path" chmod 666 /dev/null /dev/zero
    sudo chroot "$path" chmod 1777 /tmp
fi

sudo chroot --userspec=0:0 "$path" env -i HOME=/root PS1="$repo\$ " PATH=/bin:/usr/bin:/sbin:/usr/sbin TERM="$TERM" "$cmd"

exit 0