#!/bin/bash

repo="$1"
tag="$2"
cmd="$3"
folder="$HOME/.docker-internals"
path="$folder/$repo/$tag"
script_path=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
init=false
function help(){
    echo "chroot-run <repo>/<image> <tag> <command>"
    echo "Ex: chroot-run library/nginx latest bash"
    exit 0
}

if [ -z "$repo" ] || [ -z "$tag" ] || [ -z "$cmd" ]; then 
    help
fi

if [ ! -d "$path" ];then
    eval "$script_path/download-image $repo $tag"
    init=true    
fi


if [ "$init" = true ];then
    # make resolve work
    echo "nameserver 8.8.8.8" > $path/etc/resolv.conf

    # add stuff to make it usable
    sudo chroot "$path" "useradd" "$USER"
    sudo chroot "$path" "mknod" "/dev/null" "c" "1" "3"
    sudo chroot "$path" "mknod" "/dev/zero" "c" "1" "5"
    sudo chroot "$path" "chmod" "666" "/dev/null" "/dev/zero"
    sudo chroot "$path" "chmod" "1777" "/tmp"
fi

sudo chroot --userspec=$USER:$USER "$path" "$cmd"
#sudo chroot "$path" "$cmd"