#!/bin/bash
set -eo pipefail

repo=${1%*:*}
tag=${1#*:*}
cmd="$2"
images_path="$HOME/.docker-internals/images"
fs_path="$images_path/$repo/$tag"
repo_path="$images_path/$repo"
container_id=$(uuidgen)
containers_path="$HOME/.docker-internals/containers"
ns_path="$containers_path/$container_id/namespaces"
script_path=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

function die(){
    echo "Error: $1" 1>&2
    exit 1
}

function help(){
    echo "Usage: $(basename $0) <repo>/<image>:<tag>"
    exit 0
}
[[ $1 =~ ^[a-z0-9_-]+/[a-z0-9_-]+:[a-z0-9_-]+$ ]] || help

[ -n "$cmd" ] || help

if [ ! -d "$fs_path" ];then
    eval "$script_path/image-download $repo:$tag"
fi

echo "nameserver 8.8.8.8" > $fs_path/etc/resolv.conf
sudo chroot "$fs_path" chmod 1777 /tmp

cd $repo_path
sudo unshare  --uts --mount --pid --ipc --fork bash $script_path/init "$(echo $repo | cut -f2 -d/)" $tag "${@:2}"

exit 0
