#!/bin/bash
set -eo pipefail

platform="amd64"
os="linux"
repo=${1%*:*}
tag=${1#*:*}
folder="$HOME/.docker-internals"
path="$folder/$repo/$tag"

function help(){
    echo "Usage: $(basename $0) <repo>/<image>:<tag>"
    exit 0
}
[[ $1 =~ ^[a-z_-]+/[a-z_-]+:[a-z_-]+$ ]] || help

if ! command -v jq &> /dev/null; then
    echo "jq is not installed. Exiting."
    exit 1
fi

[ ! -d "$path" ] || echo "Image already downloaded in $path"; exit 1


function get_token(){
    local url="https://auth.docker.io/token?service=registry.docker.io&scope=repository:$1:pull"

    curl -s "$url" | jq -r '.token'
} 

function get_manifest(){
    local api="application/vnd.docker.distribution.manifest.v2+json"
    local apil="application/vnd.docker.distribution.manifest.list.v2+json"
    local apii="application/vnd.oci.image.manifest.v1+json"
    local url="https://registry-1.docker.io/v2/$1/manifests/$2"
    
    curl -H "Accept: ${apil}" -H "Accept: ${api}" -H "Accept: ${apii}" -H "Authorization: Bearer $3" -s "$url"
}

function get_layer(){
    local api="application/vnd.oci.image.manifest.v1+json"
    local url="https://registry-1.docker.io/v2/$1/blobs/$2"

    echo "Downloading layer: ${2#sha256:}"
    curl -L -H "Accept: ${api}" -H "Authorization: Bearer $3" -s "$url" | tar xz -C "$4"
}

token=$(get_token $repo)

resp=$(get_manifest $repo $tag $token)

if ! echo $resp | jq -e 'has("manifests")' > /dev/null; then
    echo "Image has old manifest format. Exiting."
    exit 1;
fi

digest=$(echo $resp | jq -r ".manifests | .[] | select(.platform.architecture == \"${platform}\" and .platform.os == \"${os}\") | .digest")

echo "Downloading to: $path"
mkdir -p "$path"
get_manifest $repo $digest $token | jq -r '.layers[] | .digest' | while read l; do
    get_layer $repo $l $token $path
done;